### ISSUE TITLE
Unsupervised Brain Anomaly Detection and Segmentation with Transformers

### ISSUE THREAD

**Issue by Warvito** [fahadshamshad/awesome-transformers-in-medical-imaging#1]
Please, consider adding our anomaly detection study with transformers to the list.

Unsupervised Brain Anomaly Detection and Segmentation with Transformers [23 Feb 2021]
Walter Hugo Lopez Pinaya, Petru-Daniel Tudosiu, Robert Gray, Geraint Rees, Parashkev Nachev, Sebastien Ourselin, M. Jorge Cardoso
https://arxiv.org/abs/2102.11650

**Comment by fahadshamshad** [comment]
Hi, thanks for letting us know about your interesting work. We have added it in the list.
