### ISSUE TITLE
Surface Vision Transformers: Attention-Based Modelling applied to Cortical Analysis

### ISSUE THREAD

**Issue by SD3004** [fahadshamshad/awesome-transformers-in-medical-imaging#3]
Hi, 

Great work and very helpful repository. 

Please, consider adding our work accepted at MIDL 2022 that extended the Vision Transformers for any genus-zero surface, and specifically to study the cortical surface in neonatal MRI scans. 
https://arxiv.org/abs/2203.16414

_Surface Vision Transformers: Attention-Based Modelling applied to Cortical Analysis_
Simon Dahan, Abdulah Fawaz, Logan Z. J. Williams, Chunhui Yang, Timothy S. Coalson, Matthew F. Glasser, A. David Edwards, Daniel Rueckert, Emma C. Robinson

Our code is also available at:
https://github.com/metrics-lab/surface-vision-transformers 

Thanks

**Comment by fahadshamshad** [comment]
Hi, we have added your work in the list. Thanks.
